apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-python-oypcfcia
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/backend-tests-python-oypcfcia:354f5ed1dfcc0f9b185ef9a3708ca528941c6b0f
          name: container-image
